# Generated by Django 2.2.4 on 2019-10-13 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplementary_applications', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Supplementary_Applications',
            new_name='Supplementary_Application',
        ),
    ]
