# Generated by Django 2.2.4 on 2019-10-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplementary_applications', '0002_auto_20191013_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplementary_application',
            name='university',
            field=models.CharField(choices=[('UNIVERSITY_OF_BRITISH_COLUMBIA', 'University Of British Columbia'), ('UNIVERSITY_OF_TORONTO', 'University Of Toronto'), ('UNIVERSITY_OF_WATERLOO', 'University Of Waterloo')], default=('UNIVERSITY_OF_BRITISH_COLUMBIA', 'University Of British Columbia'), max_length=30),
        ),
        migrations.AlterField(
            model_name='supplementary_application',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='supplementary_application',
            name='net_upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
