# Generated by Django 2.2.4 on 2019-10-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplementary_applications', '0003_auto_20191013_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplementary_application',
            name='university',
            field=models.CharField(choices=[('UNIVERSITY_OF_BRITISH_COLUMBIA', 'University Of British Columbia'), ('UNIVERSITY_OF_TORONTO', 'University Of Toronto'), ('UNIVERSITY_OF_WATERLOO', 'University Of Waterloo')], max_length=30),
        ),
    ]
