# Generated by Django 2.2.4 on 2019-10-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplementary_applications', '0005_supplementary_application_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplementary_application',
            name='tags',
            field=models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WAITLISTED', 'Waitlist'), ('AIF', 'AIF')], max_length=20),
        ),
    ]
