# Generated by Django 2.2.4 on 2019-10-13 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplementary_applications', '0006_auto_20191013_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplementary_application',
            name='tags',
        ),
    ]
