# Generated by Django 2.2.4 on 2019-10-13 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplementary_applications', '0010_auto_20191013_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplementary_application',
            old_name='years',
            new_name='year',
        ),
    ]
