# Generated by Django 2.2.4 on 2019-12-16 20:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplementary_applications', '0013_auto_20191017_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplementary_application',
            name='downvoters',
            field=models.ManyToManyField(related_name='downvoters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplementary_application',
            name='upvoters',
            field=models.ManyToManyField(related_name='upvoters', to=settings.AUTH_USER_MODEL),
        ),
    ]
