# Generated by Django 2.2.4 on 2019-12-18 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplementary_applications', '0014_auto_20191216_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplementary_application',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.University'),
        ),
    ]
