# Generated by Django 2.2.4 on 2019-12-18 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
        ('supplementary_applications', '0015_auto_20191218_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplementary_application',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.Program'),
        ),
    ]
