# Generated by Django 2.2.4 on 2019-12-18 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplementary_applications', '0016_supplementary_application_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplementary_application',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Program'),
        ),
    ]
