# Generated by Django 2.2.4 on 2019-12-18 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplementary_applications', '0017_auto_20191218_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplementary_application',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplementary_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
