# Generated by Django 2.2.4 on 2019-12-18 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplementary_applications', '0018_auto_20191218_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplementary_application',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_group', to='programs.Program'),
        ),
        migrations.AlterField(
            model_name='supplementary_application',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_group', to='universities.University'),
        ),
    ]
