# Generated by Django 2.2.4 on 2019-12-18 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplementary_applications', '0020_auto_20191218_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplementaryapplication',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='programs.Program'),
        ),
        migrations.AlterField(
            model_name='supplementaryapplication',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='universities.University'),
        ),
    ]
