# Generated by Django 2.2.4 on 2019-12-18 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplementary_applications', '0021_auto_20191218_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplementaryapplication',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='programs.Program'),
        ),
        migrations.AlterField(
            model_name='supplementaryapplication',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='universities.University'),
        ),
    ]
