# Generated by Django 2.2.4 on 2019-12-18 20:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplementary_applications', '0022_auto_20191218_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplementaryapplication',
            name='downvoters',
            field=models.ManyToManyField(blank=True, related_name='downvoters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supplementaryapplication',
            name='upvoters',
            field=models.ManyToManyField(blank=True, related_name='upvoters', to=settings.AUTH_USER_MODEL),
        ),
    ]
