# Generated by Django 2.2.4 on 2019-12-20 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplementary_applications', '0023_auto_20191218_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplementaryapplication',
            name='tag',
            field=models.CharField(blank=True, choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WAITLISTED', 'Waitlist'), ('AIF', 'AIF')], max_length=50),
        ),
    ]
