# Generated by Django 2.2.4 on 2019-12-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplementary_applications', '0024_supplementaryapplication_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplementaryapplication',
            name='tag',
            field=models.CharField(blank=True, choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WAITLISTED', 'Waitlist')], max_length=50),
        ),
    ]
