# Generated by Django 3.0.2 on 2020-01-15 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplementary_applications', '0025_auto_20191228_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplementaryapplication',
            name='tag',
            field=models.CharField(blank=True, choices=[('PROF_NOTES', 'Prof Notes'), ('USER_NOTES', 'User Notes')], max_length=50),
        ),
    ]
