# Generated by Django 2.2.4 on 2019-12-15 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplementary_applications', '0013_auto_20191017_0602'),
        ('accounts', '0002_auto_20191215_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='supplementary_application_posts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplementary_applications.Supplementary_Application'),
        ),
    ]
