# Generated by Django 2.2.4 on 2019-12-16 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_supplementary_application_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='supplementary_application_posts',
        ),
    ]
