# Generated by Django 2.2.4 on 2020-01-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200108_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='net_upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
