# Generated by Django 2.2.4 on 2020-01-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_net_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_contributions',
            field=models.IntegerField(default=0),
        ),
    ]
