# Generated by Django 2.2.4 on 2020-01-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_total_contributions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='tempAccount', max_length=150),
            preserve_default=False,
        ),
    ]
