# Generated by Django 2.2.4 on 2019-12-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceitem',
            name='thumbnail',
            field=models.ImageField(upload_to='images'),
        ),
    ]
