# Generated by Django 2.2.4 on 2020-01-06 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
        ('programs', '0001_initial'),
        ('resource_item', '0002_auto_20191228_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceitem',
            name='program',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='programs.Program'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourceitem',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='universities.University'),
            preserve_default=False,
        ),
    ]
