# Generated by Django 2.2.4 on 2020-01-06 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_item', '0003_auto_20200106_0410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourceitem',
            name='program',
        ),
        migrations.RemoveField(
            model_name='resourceitem',
            name='university',
        ),
    ]
