# Generated by Django 2.2.4 on 2020-01-06 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
        ('resource_item', '0004_auto_20200106_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceitem',
            name='university',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='universities.University'),
            preserve_default=False,
        ),
    ]
