# Generated by Django 2.2.4 on 2020-01-06 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource_item', '0005_resourceitem_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceitem',
            name='university',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='universities.University'),
        ),
    ]
