# Generated by Django 2.2.4 on 2020-01-06 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
        ('universities', '0001_initial'),
        ('resource_item', '0007_remove_resourceitem_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceitem',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='programs.Program'),
        ),
        migrations.AddField(
            model_name='resourceitem',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='universities.University'),
        ),
    ]
