# Generated by Django 2.2.4 on 2020-01-06 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource_item', '0009_auto_20200106_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceitem',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='programs.Program'),
        ),
    ]
