# Generated by Django 2.2.4 on 2020-01-06 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource_type', '0001_initial'),
        ('resource_item', '0010_auto_20200106_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceitem',
            name='resource_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='resource_type.ResourceType'),
        ),
    ]
