# Generated by Django 2.2.4 on 2020-01-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_item', '0012_auto_20200106_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceitem',
            name='thumbnail',
            field=models.FileField(upload_to='images'),
        ),
    ]
