# Generated by Django 2.2.4 on 2020-01-07 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_item', '0013_auto_20200107_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceitem',
            name='thumbnail',
            field=models.FileField(max_length=300, upload_to='images'),
        ),
    ]
