# Generated by Django 2.2.4 on 2020-01-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_item', '0014_auto_20200107_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceitem',
            name='thumbnail',
            field=models.ImageField(max_length=300, upload_to='images'),
        ),
    ]
