# Generated by Django 2.2.4 on 2020-01-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_item', '0015_auto_20200107_0533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourceitem',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='resourceitem',
            name='url_base',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
