# Generated by Django 2.2.4 on 2020-01-08 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource_item', '0016_auto_20200107_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceitem',
            name='url',
            field=models.CharField(default='https://google.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourceitem',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_items', to='programs.Program'),
        ),
        migrations.AlterField(
            model_name='resourceitem',
            name='resource_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_items', to='resource_type.ResourceType'),
        ),
        migrations.AlterField(
            model_name='resourceitem',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_items', to='universities.University'),
        ),
    ]
