# Generated by Django 2.2.4 on 2020-01-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_item', '0017_auto_20200108_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceitem',
            name='url',
            field=models.URLField(max_length=100),
        ),
    ]
